#!/bin/zsh
##? Add an alias to aliases

if [ $# -lt 2 ]; then
    echo "Usage: aliasadd <alias_name> <command>"
    return 1
fi

# Set alias file location
alias_file="${ZDOTDIR:-$HOME}/.zshrc.d/aliases.zsh"

if [ ! -f "$alias_file" ]; then
  echo "Error: Alias file $alias_file does not exist" >&2
  return 1
fi

if [ ! -w "$alias_file" ]; then
  echo "Error: Alias file $alias_file is not writable" >&2
  return 1
fi

# Store the alias name
alias_name="$1"

# Combine all arguments after the first one into the alias command
shift
command="$*"

escaped_command=$(cat <<EOF
'$command'
EOF
)

if grep -q "^alias $alias_name=" "$alias_file"; then
  echo "Error: Alias $alias_name already exists" >&2
  return 1
fi

if echo "alias $alias_name=$escaped_command" >> "$alias_file"; then
  # Reload the aliases file to make the new alias available
  source "$alias_file"
  echo "Alias $alias_name added for '$command'"
else
  echo "Error: Failed to add alias $alias_name to $alias_file" >&2
  return 1
fi
