add_newline = true
command_timeout = 1000

# A minimal left prompt
format = """($python$git_branch${custom.git_status_dirty}$git_status\n)$directory$character"""

# move the rest of the prompt to the right
#right_format = """$status$git_branch${custom.git_status_dirty}$git_status"""
right_format = """$status$cmd_duration"""

[character]
success_symbol = "[❯](purple)[❯](cyan)"
error_symbol = "[❯](yellow)[❯](red)"
vicmd_symbol = "[❮](purple)[❮](cyan)"
# success_symbol = "[⨠](purple)"
# error_symbol = "[⨠](red)"
# vicmd_symbol = "[⪻](yellow)"

[python]
format = '(\(($virtualenv|)${version}\) )'

[directory]
style = "blue"
truncation_length = 1
truncation_symbol = ""
fish_style_pwd_dir_length = 1

# right prompt uses left space padding
[git_branch]
format = '([$branch]($style) )([$remote_name/](red)[$remote_branch](blue) )'
always_show_remote = true
style = 'green'

[git_status]
format = '([\[$ahead_behind$stashed\]]($style))'
style = "cyan"
stashed = "≡"
ahead = "⇡${count}"
behind = "⇣${count}"

[custom.git_status_dirty]
when = 'test -n "$(git status --porcelain 2>/dev/null)"'
symbol = "↔"
style = "red"
format="[$symbol ]($style)"
shell = ["zsh"]

[cmd_duration]
format = ' [$duration]($style)'

[line_break]
disabled = true

[status]
disabled = false
symbol = ' ✘'
