#
# zephyr.toml - Zephyr default prompt theme
#

add_newline = true
command_timeout = 1000
scan_timeout = 500

# A minimal left prompt
# format = """$python$directory$character"""
format = """($python$nodejs$git_branch$conda${custom.git_status_dirty}$git_status\n)$directory$character"""

# move the rest of the prompt to the right
#right_format = """$status$git_branch${custom.git_status_dirty}$git_status"""
# right_format = """$status$cmd_duration$git_branch${custom.git_status_dirty}$git_status"""
right_format = """$status$cmd_duration"""

palette="tokyo_night_256"

# Define custom colors
[palettes.tokyo_night]
black = '#15161e'
blue = '#7aa2f7'
cyan = '#7dcfff'
green = '#9ece6a'
purple = '#bb9af7'
red = '#f7768e'
white = '#a9b1d6'
yellow = '#e0af68'

[palettes.tokyo_night_256]
black = '16'
blue = '111'
cyan = '117'
green = '149'
purple = '141'
red = '210'
white = '146'
yellow = '179'

[palettes.wombat]
black = '#000000'
blue = '#5da9f6'
cyan = '#82fff7'
green = '#b1e969'
purple = '#e86aff'
red = '#ff615a'
white = '#dedacf'
yellow = '#ebd99c'

[palettes.wombat_256]
black = '0'
blue = '75'
cyan = '123'
green = '149'
purple = '171'
red = '203'
white = '188'
yellow = '223'

[character]
success_symbol = "[❯](purple)[❯](cyan)"
error_symbol = "[❯](yellow)[❯](red)"
vicmd_symbol = "[❮](purple)[❮](cyan)"

[python]
format = '[(\(($virtualenv|)${version}\) )]($style)'
# pyenv_version_name = true
style = 'white'
version_format = 'v${raw}'

[directory]
style = "blue"
truncation_length = 1
truncation_symbol = ""
fish_style_pwd_dir_length = 1

# right prompt uses left space padding
[git_branch]
# format = ' [$branch]($style)'
format = '([$branch]($style) )([$remote_name/](red)[$remote_branch](blue) )( [\[$ahead_behind$stashed\]]($style))'
always_show_remote = true
style = 'green'

[git_status]
format = '( [\[$ahead_behind$stashed\]]($style))'
style = "cyan"
stashed = "≡"
ahead = "⇡${count}"
behind = "⇣${count}"

[custom.git_status_dirty]
when = 'test -n "$(git status --porcelain 2>/dev/null)"'
symbol = "•"
style = "red"
format="[$symbol]($style)"
ignore_timeout=true
shell = ["sh"]

[cmd_duration]
format = ' [$duration]($style)'

[line_break]
disabled = true

[status]
disabled = false
symbol = ' ✘'
